# Generated by Django 4.1.1 on 2022-10-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="place",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quantity",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="device",
            field=models.ManyToManyField(
                blank=True, null=True, to="orders.devicesservice"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="snack",
            field=models.ManyToManyField(
                blank=True, null=True, to="orders.snacksservice"
            ),
        ),
    ]
