# Generated by Django 4.1.1 on 2022-10-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_active_order_place_quantity_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quantity",
            options={
                "verbose_name": "Комментарии к новостью",
                "verbose_name_plural": "Комментарии к новостям",
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="lavozim",
            new_name="position",
        ),
    ]
