# Generated by Django 4.1.1 on 2022-10-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_quantity_options_rename_lavozim_order_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="snack",
        ),
    ]
