# Generated by Django 4.1.1 on 2022-10-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_is_deleted_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="people",
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quantity",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="orders.order",
            ),
        ),
    ]
